[package]
name = "bitcoin"
version = "0.18.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/rust-bitcoin/rust-bitcoin/"
repository = "https://github.com/rust-bitcoin/rust-bitcoin/"
documentation = "https://docs.rs/bitcoin/"
description = "General purpose library for using and interoperating with Bitcoin and other cryptocurrencies."
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[lib]
name = "bitcoin"
path = "src/lib.rs"

[features]
fuzztarget = ["secp256k1/fuzztarget", "bitcoin_hashes/fuzztarget"]
serde-decimal = ["use-serde", "strason"]
unstable = []
use-serde = ["serde", "serde_test", "bitcoin_hashes/serde"]

[dependencies]
bitcoin-bech32 = "0.9.0"
byteorder = "1.2"
rand = "0.3"
bitcoin_hashes = { git = "https://github.com/stevenroose/bitcoin_hashes", rev = "29053f647eb9c587cd87b34be38b0050ff26a7af" }
bitcoinconsensus = { version = "0.16", optional = true }

[dev-dependencies]
tempfile = "3"

[dependencies.serde]
version = "1"
optional = true

[dependencies.serde_test]
version = "1"
optional = true

[dependencies.strason]
version = "0.4"
optional = true
default-features = false

[dependencies.hex]
version = "=0.3.2"

[dependencies.secp256k1]
version = "0.12"
features = [ "rand" ]
